import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { en } from "../src/i18n/en.ts";
import { de as originalDe } from "../src/i18n/de.ts";
import { es as originalEs } from "../src/i18n/es.ts";
import { fr as originalFr } from "../src/i18n/fr.ts";
import { zh as originalZh } from "../src/i18n/zh.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const deTranslations: Record<string, string> = {
  "worktree.already_selected_callback": "Dieses Worktree ist bereits ausgewählt",
  "worktree.empty": "📭 Keine Git-Worktrees für das aktuelle Repository gefunden.",
  "worktree.fetch_error": "🔴 Git-Worktrees konnten nicht geladen werden.",
  "worktree.not_git_repo": "🌿 Git-Worktrees sind für das aktuelle Projekt nicht verfügbar. Wähle zuerst ein Git-Repository aus.",
  "worktree.not_git_repo_callback": "Das aktuelle Projekt ist kein Git-Repository",
  "worktree.page_empty_callback": "Keine Worktrees auf dieser Seite",
  "worktree.project_not_selected": "🏗 Projekt ist nicht ausgewählt.\n\nWähle zuerst ein Projekt mit /projects.",
  "worktree.select_error": "🔴 Worktree konnte nicht ausgewählt werden.",
  "worktree.select_with_current": "Wähle ein Worktree aus:",
  "worktree.selected": "✅ Worktree ausgewählt: {worktree}\n\n📋 Sitzung wurde zurückgesetzt. Nutze /sessions oder /new, um fortzufahren.",
  "worktree.selection_missing_callback": "Das ausgewählte Worktree ist nicht mehr verfügbar",

  "technical_progress.file_read.running": "Datei wird gelesen",
  "technical_progress.file_read.success": "Datei gelesen",
  "technical_progress.file_read.failure": "Fehler beim Lesen der Datei",
  "technical_progress.file_read.empty": "Datei gelesen",
  "technical_progress.directory_read.running": "Verzeichnis wird gelesen",
  "technical_progress.directory_read.success": "Verzeichnis gelesen",
  "technical_progress.directory_read.failure": "Fehler beim Lesen des Verzeichnisses",
  "technical_progress.directory_read.empty": "Verzeichnis gelesen",
  "technical_progress.file_write.running": "Datei wird geschrieben",
  "technical_progress.file_write.success": "Datei geschrieben",
  "technical_progress.file_write.failure": "Fehler beim Schreiben der Datei",
  "technical_progress.file_write.empty": "Datei geschrieben",
  "technical_progress.file_edit.running": "Datei wird bearbeitet",
  "technical_progress.file_edit.success": "Datei bearbeitet",
  "technical_progress.file_edit.failure": "Fehler beim Bearbeiten der Datei",
  "technical_progress.file_edit.empty": "Datei bearbeitet",
  "technical_progress.file_create.running": "Datei wird erstellt",
  "technical_progress.file_create.success": "Datei erstellt",
  "technical_progress.file_create.failure": "Fehler beim Erstellen der Datei",
  "technical_progress.file_create.empty": "Datei erstellt",
  "technical_progress.file_delete.running": "Datei wird gelöscht",
  "technical_progress.file_delete.success": "Datei gelöscht",
  "technical_progress.file_delete.failure": "Fehler beim Löschen der Datei",
  "technical_progress.file_delete.empty": "Datei gelöscht",
  "technical_progress.patch.running": "Patch wird angewendet",
  "technical_progress.patch.success": "Patch angewendet",
  "technical_progress.patch.failure": "Fehler beim Anwenden des Patches",
  "technical_progress.patch.empty": "Patch angewendet",
  "technical_progress.command.running": "Befehl wird ausgeführt",
  "technical_progress.command.success": "Befehl ausgeführt",
  "technical_progress.command.failure": "Befehl fehlgeschlagen",
  "technical_progress.command.empty": "Befehl ausgeführt",
  "technical_progress.project_search.running": "Projekt wird durchsucht",
  "technical_progress.project_search.success": "Übereinstimmungen gefunden",
  "technical_progress.project_search.failure": "Suche fehlgeschlagen",
  "technical_progress.project_search.empty": "Keine Übereinstimmungen gefunden",
  "technical_progress.web_search.running": "Web-Suche läuft",
  "technical_progress.web_search.success": "Web durchsucht",
  "technical_progress.web_search.failure": "Web-Suche fehlgeschlagen",
  "technical_progress.web_search.empty": "Keine Web-Ergebnisse gefunden",
  "technical_progress.web_read.running": "Seite wird gelesen",
  "technical_progress.web_read.success": "Seite gelesen",
  "technical_progress.web_read.failure": "Fehler beim Lesen der Seite",
  "technical_progress.web_read.empty": "Seite gelesen",
  "technical_progress.reasoning.running": "Denkvorgang läuft",
  "technical_progress.reasoning.success": "Denkvorgang beendet",
  "technical_progress.reasoning.failure": "Denkvorgang fehlgeschlagen",
  "technical_progress.reasoning.empty": "Denkvorgang beendet",
  "technical_progress.skill.running": "Skill wird ausgeführt",
  "technical_progress.skill.success": "Skill abgeschlossen",
  "technical_progress.skill.failure": "Skill fehlgeschlagen",
  "technical_progress.skill.empty": "Skill abgeschlossen",
  "technical_progress.subagent.running": "Subagent arbeitet",
  "technical_progress.subagent.success": "Subagent fertig",
  "technical_progress.subagent.failure": "Subagent fehlgeschlagen",
  "technical_progress.subagent.empty": "Subagent fertig",
  "technical_progress.mcp.running": "MCP-Werkzeug wird ausgeführt",
  "technical_progress.mcp.success": "MCP-Werkzeug abgeschlossen",
  "technical_progress.mcp.failure": "MCP-Werkzeug fehlgeschlagen",
  "technical_progress.mcp.empty": "MCP-Werkzeug abgeschlossen",
  "technical_progress.todo.running": "Aufgabenliste wird aktualisiert",
  "technical_progress.todo.success": "Aufgabenliste aktualisiert",
  "technical_progress.todo.failure": "Fehler beim Aktualisieren der Aufgabenliste",
  "technical_progress.todo.empty": "Aufgabenliste aktualisiert",
  "technical_progress.network.running": "Netzwerkanfrage läuft",
  "technical_progress.network.success": "Netzwerkanfrage abgeschlossen",
  "technical_progress.network.failure": "Netzwerkanfrage fehlgeschlagen",
  "technical_progress.network.empty": "Netzwerkanfrage abgeschlossen",
  "technical_progress.package.running": "Paket wird aktualisiert",
  "technical_progress.package.success": "Paket aktualisiert",
  "technical_progress.package.failure": "Paketoperation fehlgeschlagen",
  "technical_progress.package.empty": "Paket aktualisiert",
  "technical_progress.build.running": "Erstellung läuft",
  "technical_progress.build.success": "Erstellung abgeschlossen",
  "technical_progress.build.failure": "Erstellung fehlgeschlagen",
  "technical_progress.build.empty": "Erstellung abgeschlossen",
  "technical_progress.test.running": "Tests laufen",
  "technical_progress.test.success": "Tests abgeschlossen",
  "technical_progress.test.failure": "Tests fehlgeschlagen",
  "technical_progress.test.empty": "Tests abgeschlossen",
  "technical_progress.generic.running": "Aktion wird ausgeführt",
  "technical_progress.generic.success": "Aktion abgeschlossen",
  "technical_progress.generic.failure": "Aktion fehlgeschlagen",
  "technical_progress.generic.empty": "Aktion abgeschlossen",
  "technical_progress.todo.updated": "📝 Aufgabenliste aktualisiert — {count} {unit}",
  "technical_progress.todo.all_done": "✅ Alle Aufgaben abgeschlossen",
  "technical_progress.unit.line.one": "Zeile",
  "technical_progress.unit.line.few": "Zeilen",
  "technical_progress.unit.line.many": "Zeilen",
  "technical_progress.unit.line.other": "Zeilen",
  "technical_progress.unit.result.one": "Ergebnis",
  "technical_progress.unit.result.few": "Ergebnisse",
  "technical_progress.unit.result.many": "Ergebnisse",
  "technical_progress.unit.result.other": "Ergebnisse",
  "technical_progress.unit.task.one": "Aufgabe",
  "technical_progress.unit.task.few": "Aufgaben",
  "technical_progress.unit.task.many": "Aufgaben",
  "technical_progress.unit.task.other": "Aufgaben",
  "technical_progress.unit.item.one": "Element",
  "technical_progress.unit.item.few": "Elemente",
  "technical_progress.unit.item.many": "Elemente",
  "technical_progress.unit.item.other": "Elemente",

  "agent.mode.plan": "Der Agent plant, bevor er handelt, es wird kein Code geändert",
  "agent.mode.build": "Codeänderungen werden direkt auf Dateien angewendet",
  "agent.mode.general": "Mehrzweck-Agent für beliebige Aufgaben",
  "agent.mode.explore": "Schnelle Datei- und Codemustersuche",
  "agent.mode.title": "Generiert einen Sitzungstitel aus dem Gespräch",
  "agent.mode.summary": "Komprimiert den Gesprächsverlauf in eine Zusammenfassung",
  "agent.mode.compaction": "Fasst alte Nachrichten zusammen, um Kontext freizugeben",
  "agent.mode.custom": "Benutzerdefinierter Agenten-Modus",

  "terminal.open_button": "🖥 Terminal öffnen",
  "terminal.created": "🖥 Terminal-Thema erstellt: {title}",
  "terminal.new_topic_name": "📓 Neues Terminal",
  "terminal.topic_name": "📓 Terminal: {command}",

  "keyboard.new_window": "➕ Neues Fenster",
  "keyboard.stop": "⏹ Stopp",
  "keyboard.new_window_created": "✅ Neues Terminalfenster erstellt.",

  "reasoning.title": "🧠 Denk-Einstellungen",
  "reasoning.mode_0": "0 - Nur endgültige Antwort",
  "reasoning.mode_1": "1 - Gedanken und Dateien",
  "reasoning.mode_2": "2 - Ebene 1 + Befehle + separate Werkzeugnachrichten (Standard)",
  "reasoning.current": "Aktueller Modus: {mode}",
  "reasoning.updated": "✅ Denk-Modus geändert auf: {mode}",

  "cmd.description.compact": "Kontext der aktuellen Sitzung komprimieren",
  "cmd.description.terminal": "Terminalfenster öffnen",
  "error.user_not_found": "❌ Benutzer nicht gefunden.",
  "bot.session_recreated_remote": "🔄 Sitzung auf Remote-Server wiederhergestellt.",

  "goal.described": "🎯 Ziel beschrieben",
  "goal.paused": "⏸ Ziel pausiert",
  "goal.resumed": "▶️ Ziel fortgesetzt",
  "goal.cleared": "🧹 Ziel gelöscht",
  "goal.no_session": "❌ Keine aktive Sitzung",
  "goal.set": "🎯 Ziel gesetzt",
  "goal.error": "❌ Ziel-Fehler",

  "ssh.prompt.conn_str": "🔌 Bitte sende die SSH-Verbindungszeichenfolge im Format `username@host:port` (z. B. `root@192.168.1.100:22`)",
  "ssh.prompt.auth_method": "🔑 Wähle die SSH-Authentifizierungsmethode aus:",
  "ssh.prompt.password": "💬 Bitte sende dein SSH-Passwort:",
  "ssh.prompt.private_key": "📝 Bitte füge den Inhalt deines privaten SSH-Schlüssels ein:",
  "ssh.prompt.target": "🚀 Wähle das Bereitstellungsziel für den OpenCode-Server aus:",
  "ssh.success": "✅ SSH-Verbindung und OpenCode-Tunnel erfolgreich hergestellt!",
  "ssh.error": "🔴 SSH-Einrichtungsfehler: {error}",
  "ssh.button.password": "🔑 Passwort",
  "ssh.button.private_key": "📝 Privater Schlüssel",
  "ssh.button.docker": "🐳 Docker-Container",
  "ssh.button.host": "💻 Host-System",
  "ssh.button.cancel": "❌ Abbrechen",
  "ssh.cancelled": "❌ SSH-Konfiguration abgebrochen.",
  "ssh.active_status": "🟢 SSH aktiv: {username}@{host}:{port}",
  "ssh.button.disconnect": "🔌 Trennen",
  "ssh.button.new_connection": "➕ Neue Verbindung",
  "ssh.saved_connections_title": "📋 Gespeicherte SSH-Verbindungen:",
  "ssh.no_saved_connections": "Keine gespeicherten SSH-Verbindungen gefunden.",
  "ssh.connection_deleted": "🗑️ Verbindung gelöscht.",
  "ssh.invalid_format": "❌ Ungültiges Format. Beispiel: root@192.168.1.1:22",
  "ssh.connection_not_found": "Verbindung nicht gefunden.",
  "ssh.connecting_saved": "⏳ Verbindung zum gespeicherten Server wird hergestellt...",

  "model.menu.add_provider": "Provider hinzufügen",
  "mcp.oauth_error": "MCP-OAuth fehlgeschlagen: {error}",
  "mcp.oauth_success": "MCP-OAuth für {name} abgeschlossen.",
  "mcp.oauth_starting": "OAuth für {name} wird gestartet...",
  "mcps.button.oauth": "Authentifizieren",
  "share.unshared": "Sitzungsfreigabe widerrufen.",
  "share.unshare_error": "Sitzungsfreigabe konnte nicht widerrufen werden.",
  "share.success": "Sitzung freigegeben: {url}",
  "share.error": "Sitzung konnte nicht freigegeben werden.",
  "share.no_session": "Keine aktive Sitzung zum Freigeben.",
  "cmd.description.share": "Aktuelle Sitzung freigeben",
  "server.unavailable": "Server ist nicht verfügbar.",
  "server.healthy": "Server ist betriebsbereit.",
  "server.credentials": "Benutzername: ||{user}||\nPasswort: ||{pass}||",
  "server.info": "OpenCode-Server: {url}",
  "cmd.description.server": "OpenCode Web-Panel",

  "connect.oauth_polling": "Warte auf Autorisierung... Der Server erkennt dies automatisch (der Browser muss sich auf derselben Maschine befinden).",
  "connect.oauth_checking": "Autorisierungsstatus wird geprüft...",
  "connect.oauth_timeout": "Zeitüberschreitung bei der Autorisierung für {name}. Bitte versuche es erneut oder verwende die API-Schlüssel-Methode.",
  "connect.ready": "Server neu gestartet.",
  "connect.restarting": "Server wird neu gestartet...",
  "connect.enter_key": "API-Schlüssel für {name} eingeben:",
  "connect.no_methods": "Keine Authentifizierungsmethoden verfügbar.",
  "connect.choose_method": "Authentifizierungsmethode auswählen:",
  "connect.pick": "Anbieter auswählen:",
  "connect.authorized": "Erfolgreich beim Anbieter autorisiert.",
  "connect.auth_url": "Öffne diese URL zur Authentifizierung:\n{url}",
  "connect.auth_error": "Authentifizierung fehlgeschlagen. Bitte versuche es erneut.",
  "connect.select": "Wähle einen Anbieter zum Verbinden:",
  "connect.empty": "Keine KI-Anbieter konfiguriert.",
  "connect.error": "Anbieter konnten nicht aufgelistet werden.",
  "cmd.description.connect": "KI-Anbieter verbinden",

  "cmd.description.fork": "Sitzung in neues Thema abspalten",
  "fork.success": "Sitzung abgespalten: {title}. Wird in neuem Thema geöffnet...",
  "fork.no_session": "Keine aktive Sitzung zum Abspalten.",
  "fork.error": "Abspalten der Sitzung fehlgeschlagen.",
  "share.already_shared": "Sitzung bereits freigegeben: {url}",
  "edit.fork_or_revert": "Nachricht bearbeitet. Aktion wählen:",
  "edit.fork_button": "In neuem Thema abspalten",
  "edit.revert_button": "Auf diese Nachricht zurücksetzen",
  "edit.no_session": "Bearbeitete Nachricht kann nicht verarbeitet werden: keine aktive Sitzung.",
  "edit.not_found": "Bearbeitete Nachricht nicht im Journal erfasst.",
  "cmd.description.revert": "Sitzung auf beantwortete Nachricht zurücksetzen",
  "cmd.description.del": "Beantwortete Nachricht löschen",
  "revert.no_reply": "Antworte auf eine Nachricht mit /revert, um auf diese zurückzusetzen.",
  "revert.no_session": "Keine aktive Sitzung.",
  "revert.error": "Zurücksetzen der Sitzung fehlgeschlagen.",
  "revert.success": "Sitzung zurückgesetzt. Nachrichten aus dem Thema gelöscht.",
  "del.no_reply": "Antworte auf eine Nachricht mit /del, um sie zu löschen.",
  "del.success": "Nachricht gelöscht.",
  "del.error": "Löschen der Nachricht fehlgeschlagen.",
  "bookmark.saved": "❤️ Nachricht als Lesezeichen gespeichert.",
  "bookmark.removed": "Lesezeichen entfernt.",
  "react.abort": "💔 Vorgang abgebrochen.",
  "cmd.description.memory": "Projektspeicher anzeigen (MEMORY.md)",
  "memory.empty": "MEMORY.md nicht gefunden. Nutze /memory add <Text> zum Erstellen.",
  "memory.added": "Eintrag zu MEMORY.md hinzugefügt.",
  "memory.usage": "Verwendung: /memory [add <Text>] — Speicher anzeigen oder ergänzen.",
  "memory.show": "Projektspeicher (MEMORY.md):",
  "memory.show_truncated": "(zeige die ersten 2000 Zeichen)"
};

const esTranslations: Record<string, string> = {
  "worktree.already_selected_callback": "Este worktree ya está seleccionado",
  "worktree.empty": "📭 No se encontraron worktrees de git para el repositorio actual.",
  "worktree.fetch_error": "🔴 No se pudieron cargar los worktrees de git.",
  "worktree.not_git_repo": "🌿 Los worktrees de git no están disponibles para el proyecto actual. Selecciona primero un repositorio de git.",
  "worktree.not_git_repo_callback": "El proyecto actual no es un repositorio de git",
  "worktree.page_empty_callback": "No hay worktrees en esta página",
  "worktree.project_not_selected": "🏗 No hay un proyecto seleccionado.\n\nPrimero selecciona un proyecto con /projects.",
  "worktree.select_error": "🔴 No se pudo seleccionar el worktree.",
  "worktree.select_with_current": "Selecciona un worktree:",
  "worktree.selected": "✅ Worktree seleccionado: {worktree}\n\n📋 La sesión se reinició. Usa /sessions o /new para continuar.",
  "worktree.selection_missing_callback": "El worktree seleccionado ya no está disponible",

  "technical_progress.file_read.running": "Leyendo archivo",
  "technical_progress.file_read.success": "Archivo leído",
  "technical_progress.file_read.failure": "Error al leer el archivo",
  "technical_progress.file_read.empty": "Archivo leído",
  "technical_progress.directory_read.running": "Leyendo directorio",
  "technical_progress.directory_read.success": "Directorio leído",
  "technical_progress.directory_read.failure": "Error al leer el directorio",
  "technical_progress.directory_read.empty": "Directorio leído",
  "technical_progress.file_write.running": "Escribiendo archivo",
  "technical_progress.file_write.success": "Archivo escrito",
  "technical_progress.file_write.failure": "Error al escribir el archivo",
  "technical_progress.file_write.empty": "Archivo escrito",
  "technical_progress.file_edit.running": "Editando archivo",
  "technical_progress.file_edit.success": "Archivo editado",
  "technical_progress.file_edit.failure": "Error al editar el archivo",
  "technical_progress.file_edit.empty": "Archivo editado",
  "technical_progress.file_create.running": "Creando archivo",
  "technical_progress.file_create.success": "Archivo creado",
  "technical_progress.file_create.failure": "Error al crear el archivo",
  "technical_progress.file_create.empty": "Archivo creado",
  "technical_progress.file_delete.running": "Eliminando archivo",
  "technical_progress.file_delete.success": "Archivo eliminado",
  "technical_progress.file_delete.failure": "Error al eliminar el archivo",
  "technical_progress.file_delete.empty": "Archivo eliminado",
  "technical_progress.patch.running": "Aplicando parche",
  "technical_progress.patch.success": "Parche aplicado",
  "technical_progress.patch.failure": "Error al aplicar el parche",
  "technical_progress.patch.empty": "Parche aplicado",
  "technical_progress.command.running": "Ejecutando comando",
  "technical_progress.command.success": "Comando ejecutado",
  "technical_progress.command.failure": "Comando fallido",
  "technical_progress.command.empty": "Comando ejecutado",
  "technical_progress.project_search.running": "Buscando en el proyecto",
  "technical_progress.project_search.success": "Coincidencias encontradas",
  "technical_progress.project_search.failure": "Búsqueda fallida",
  "technical_progress.project_search.empty": "No se encontraron coincidencias",
  "technical_progress.web_search.running": "Buscando en la web",
  "technical_progress.web_search.success": "Web buscada",
  "technical_progress.web_search.failure": "Búsqueda web fallida",
  "technical_progress.web_search.empty": "No se encontraron resultados web",
  "technical_progress.web_read.running": "Leyendo página",
  "technical_progress.web_read.success": "Página leída",
  "technical_progress.web_read.failure": "Error al leer la página",
  "technical_progress.web_read.empty": "Página leída",
  "technical_progress.reasoning.running": "Pensando",
  "technical_progress.reasoning.success": "Razonamiento finalizado",
  "technical_progress.reasoning.failure": "Error de razonamiento",
  "technical_progress.reasoning.empty": "Razonamiento finalizado",
  "technical_progress.skill.running": "Ejecutando skill",
  "technical_progress.skill.success": "Skill completada",
  "technical_progress.skill.failure": "Skill fallida",
  "technical_progress.skill.empty": "Skill completada",
  "technical_progress.subagent.running": "Subagente trabajando",
  "technical_progress.subagent.success": "Subagente finalizado",
  "technical_progress.subagent.failure": "Subagente fallido",
  "technical_progress.subagent.empty": "Subagente finalizado",
  "technical_progress.mcp.running": "Ejecutando herramienta MCP",
  "technical_progress.mcp.success": "Herramienta MCP completada",
  "technical_progress.mcp.failure": "Herramienta MCP fallida",
  "technical_progress.mcp.empty": "Herramienta MCP completada",
  "technical_progress.todo.running": "Actualizando lista de tareas",
  "technical_progress.todo.success": "Lista de tareas actualizada",
  "technical_progress.todo.failure": "Error al actualizar la lista de tareas",
  "technical_progress.todo.empty": "Lista de tareas actualizada",
  "technical_progress.network.running": "Ejecutando solicitud de red",
  "technical_progress.network.success": "Solicitud de red completada",
  "technical_progress.network.failure": "Solicitud de red fallida",
  "technical_progress.network.empty": "Solicitud de red completada",
  "technical_progress.package.running": "Actualizando paquete",
  "technical_progress.package.success": "Paquete actualizado",
  "technical_progress.package.failure": "Operación de paquete fallida",
  "technical_progress.package.empty": "Paquete actualizado",
  "technical_progress.build.running": "Compilando",
  "technical_progress.build.success": "Compilación completada",
  "technical_progress.build.failure": "Compilación fallida",
  "technical_progress.build.empty": "Compilación completada",
  "technical_progress.test.running": "Ejecutando pruebas",
  "technical_progress.test.success": "Pruebas completadas",
  "technical_progress.test.failure": "Pruebas fallidas",
  "technical_progress.test.empty": "Pruebas completadas",
  "technical_progress.generic.running": "Ejecutando acción",
  "technical_progress.generic.success": "Acción completada",
  "technical_progress.generic.failure": "Acción fallida",
  "technical_progress.generic.empty": "Acción completada",
  "technical_progress.todo.updated": "📝 Lista de tareas actualizada — {count} {unit}",
  "technical_progress.todo.all_done": "✅ Todas las tareas completadas",
  "technical_progress.unit.line.one": "línea",
  "technical_progress.unit.line.few": "líneas",
  "technical_progress.unit.line.many": "líneas",
  "technical_progress.unit.line.other": "líneas",
  "technical_progress.unit.result.one": "resultado",
  "technical_progress.unit.result.few": "resultados",
  "technical_progress.unit.result.many": "resultados",
  "technical_progress.unit.result.other": "resultados",
  "technical_progress.unit.task.one": "tarea",
  "technical_progress.unit.task.few": "tareas",
  "technical_progress.unit.task.many": "tareas",
  "technical_progress.unit.task.other": "tareas",
  "technical_progress.unit.item.one": "elemento",
  "technical_progress.unit.item.few": "elementos",
  "technical_progress.unit.item.many": "elementos",
  "technical_progress.unit.item.other": "elementos",

  "agent.mode.plan": "El agente planifica antes de actuar; no se modifica el código",
  "agent.mode.build": "Los cambios de código se aplican directamente a los archivos",
  "agent.mode.general": "Agente de propósito general para cualquier tarea",
  "agent.mode.explore": "Búsqueda rápida de archivos y patrones de código",
  "agent.mode.title": "Genera un título de sesión a partir de la conversación",
  "agent.mode.summary": "Comprime el historial de conversación en un resumen",
  "agent.mode.compaction": "Resume los mensajes antiguos para liberar contexto",
  "agent.mode.custom": "Modo de agente personalizado",

  "terminal.open_button": "🖥 Abrir Terminal",
  "terminal.created": "🖥 Tema de terminal creado: {title}",
  "terminal.new_topic_name": "📓 Nueva terminal",
  "terminal.topic_name": "📓 Terminal: {command}",

  "keyboard.new_window": "➕ Nueva ventana",
  "keyboard.stop": "⏹ Detener",
  "keyboard.new_window_created": "✅ Nueva ventana de terminal creada.",

  "reasoning.title": "🧠 Configuración de razonamiento",
  "reasoning.mode_0": "0 - Solo respuesta final",
  "reasoning.mode_1": "1 - Pensamientos y archivos",
  "reasoning.mode_2": "2 - Nivel 1 + comandos + mensajes de herramientas separados (predeterminado)",
  "reasoning.current": "Modo actual: {mode}",
  "reasoning.updated": "✅ Modo de razonamiento cambiado a: {mode}",

  "cmd.description.compact": "Compactar el contexto de la sesión actual",
  "cmd.description.terminal": "Abrir ventana de terminal",
  "error.user_not_found": "❌ Usuario no encontrado.",
  "bot.session_recreated_remote": "🔄 Sesión recreada en el servidor remoto.",

  "goal.described": "🎯 Objetivo descrito",
  "goal.paused": "⏸ Objetivo pausado",
  "goal.resumed": "▶️ Objetivo reanudado",
  "goal.cleared": "🧹 Objetivo borrado",
  "goal.no_session": "❌ No hay una sesión activa",
  "goal.set": "🎯 Objetivo establecido",
  "goal.error": "❌ Error de objetivo",

  "ssh.prompt.conn_str": "🔌 Envía la cadena de conexión SSH en formato `username@host:port` (p. ej., `root@192.168.1.100:22`)",
  "ssh.prompt.auth_method": "🔑 Selecciona el método de autenticación SSH:",
  "ssh.prompt.password": "💬 Envía tu contraseña SSH:",
  "ssh.prompt.private_key": "📝 Pega el contenido de tu clave privada SSH:",
  "ssh.prompt.target": "🚀 Selecciona el destino de despliegue para el servidor OpenCode:",
  "ssh.success": "✅ ¡Conexión SSH y túnel OpenCode establecidos correctamente!",
  "ssh.error": "🔴 Error de configuración SSH: {error}",
  "ssh.button.password": "🔑 Contraseña",
  "ssh.button.private_key": "📝 Clave privada",
  "ssh.button.docker": "🐳 Contenedor Docker",
  "ssh.button.host": "💻 Sistema host",
  "ssh.button.cancel": "❌ Cancelar",
  "ssh.cancelled": "❌ Configuración SSH cancelada.",
  "ssh.active_status": "🟢 SSH activo: {username}@{host}:{port}",
  "ssh.button.disconnect": "🔌 Desconectar",
  "ssh.button.new_connection": "➕ Nueva conexión",
  "ssh.saved_connections_title": "📋 Conexiones SSH guardadas:",
  "ssh.no_saved_connections": "No se encontraron conexiones SSH guardadas.",
  "ssh.connection_deleted": "🗑️ Conexión eliminada.",
  "ssh.invalid_format": "❌ Formato inválido. Ejemplo: root@192.168.1.1:22",
  "ssh.connection_not_found": "Conexión no encontrada.",
  "ssh.connecting_saved": "⏳ Conectando al servidor guardado...",

  "model.menu.add_provider": "Agregar proveedor",
  "mcp.oauth_error": "OAuth de MCP fallido: {error}",
  "mcp.oauth_success": "OAuth de MCP completado para {name}.",
  "mcp.oauth_starting": "Iniciando OAuth para {name}...",
  "mcps.button.oauth": "Autenticar",
  "share.unshared": "Compartición de sesión revocada.",
  "share.unshare_error": "Error al revocar la compartición de la sesión.",
  "share.success": "Sesión compartida: {url}",
  "share.error": "Error al compartir la sesión.",
  "share.no_session": "No hay una sesión activa para compartir.",
  "cmd.description.share": "Compartir sesión actual",
  "server.unavailable": "El servidor no está disponible.",
  "server.healthy": "El servidor está saludable.",
  "server.credentials": "Usuario: ||{user}||\nContraseña: ||{pass}||",
  "server.info": "Servidor OpenCode: {url}",
  "cmd.description.server": "Panel web de OpenCode",

  "connect.oauth_polling": "Esperando autorización... El servidor la detectará automáticamente (el navegador debe estar en la misma máquina).",
  "connect.oauth_checking": "Comprobando el estado de autorización...",
  "connect.oauth_timeout": "Tiempo de espera de autorización agotado para {name}. Por favor, inténtalo de nuevo o usa el método de clave API.",
  "connect.ready": "Servidor reiniciado.",
  "connect.restarting": "Reiniciando servidor...",
  "connect.enter_key": "Introduce la clave API para {name}:",
  "connect.no_methods": "No hay métodos de autenticación disponibles.",
  "connect.choose_method": "Elegir método de autenticación:",
  "connect.pick": "Seleccionar un proveedor:",
  "connect.authorized": "Autorizado correctamente con el proveedor.",
  "connect.auth_url": "Abre esta URL para autenticarte:\n{url}",
  "connect.auth_error": "Autenticación fallida. Por favor, inténtalo de nuevo.",
  "connect.select": "Selecciona un proveedor para conectar:",
  "connect.empty": "No hay proveedores de IA configurados.",
  "connect.error": "Error al listar los proveedores.",
  "cmd.description.connect": "Conectar proveedores de IA",

  "cmd.description.fork": "Bifurcar sesión en un nuevo tema",
  "fork.success": "Sesión bifurcada: {title}. Abriendo en un nuevo tema...",
  "fork.no_session": "No hay una sesión activa para bifurcar.",
  "fork.error": "Error al bifurcar la sesión.",
  "share.already_shared": "Sesión ya compartida: {url}",
  "edit.fork_or_revert": "Mensaje editado. Elige una acción:",
  "edit.fork_button": "Bifurcar en nuevo tema",
  "edit.revert_button": "Revertir a este mensaje",
  "edit.no_session": "No se puede procesar el mensaje editado: no hay una sesión activa.",
  "edit.not_found": "El mensaje editado no está registrado en el diario.",
  "cmd.description.revert": "Revertir sesión al mensaje respondido",
  "cmd.description.del": "Eliminar mensaje respondido",
  "revert.no_reply": "Responde a un mensaje con /revert para revertir la sesión a ese punto.",
  "revert.no_session": "No hay una sesión activa.",
  "revert.error": "Error al revertir la sesión.",
  "revert.success": "Sesión revertida. Mensajes eliminados del tema.",
  "del.no_reply": "Responde a un mensaje con /del para eliminarlo.",
  "del.success": "Mensaje eliminado.",
  "del.error": "Error al eliminar el mensaje.",
  "bookmark.saved": "❤️ Mensaje guardado en marcadores.",
  "bookmark.removed": "Marcador eliminado.",
  "react.abort": "💔 Operación cancelada.",
  "cmd.description.memory": "Mostrar memoria del proyecto (MEMORY.md)",
  "memory.empty": "MEMORY.md no encontrado. Usa /memory add <texto> para crear.",
  "memory.added": "Entrada añadida a MEMORY.md.",
  "memory.usage": "Uso: /memory [add <texto>] — mostrar o añadir a la memoria.",
  "memory.show": "Memoria del proyecto (MEMORY.md):",
  "memory.show_truncated": "(mostrando primeros 2000 caracteres)"
};

const frTranslations: Record<string, string> = {
  "worktree.already_selected_callback": "Ce worktree est déjà sélectionné",
  "worktree.empty": "📭 Aucun worktree git trouvé pour le dépôt actuel.",
  "worktree.fetch_error": "🔴 Impossible de charger les worktrees git.",
  "worktree.not_git_repo": "🌿 Les worktrees git sont indisponibles pour le projet actuel. Sélectionnez d'abord un dépôt git.",
  "worktree.not_git_repo_callback": "Le projet actuel n'est pas un dépôt git",
  "worktree.page_empty_callback": "Aucun worktree sur cette page",
  "worktree.project_not_selected": "🏗 Aucun projet n'est sélectionné.\n\nSélectionnez d'abord un projet avec /projects.",
  "worktree.select_error": "🔴 Impossible de sélectionner le worktree.",
  "worktree.select_with_current": "Sélectionnez un worktree :",
  "worktree.selected": "✅ Worktree sélectionné : {worktree}\n\n📋 La session a été réinitialisée. Utilisez /sessions ou /new pour continuer.",
  "worktree.selection_missing_callback": "Le worktree sélectionné n'est plus disponible",

  "technical_progress.file_read.running": "Lecture du fichier en cours",
  "technical_progress.file_read.success": "Fichier lu",
  "technical_progress.file_read.failure": "Échec de la lecture du fichier",
  "technical_progress.file_read.empty": "Fichier lu",
  "technical_progress.directory_read.running": "Lecture du répertoire en cours",
  "technical_progress.directory_read.success": "Répertoire lu",
  "technical_progress.directory_read.failure": "Échec de la lecture du répertoire",
  "technical_progress.directory_read.empty": "Répertoire lu",
  "technical_progress.file_write.running": "Écriture du fichier en cours",
  "technical_progress.file_write.success": "Fichier écrit",
  "technical_progress.file_write.failure": "Échec de l'écriture du fichier",
  "technical_progress.file_write.empty": "Fichier écrit",
  "technical_progress.file_edit.running": "Modification du fichier en cours",
  "technical_progress.file_edit.success": "Fichier modifié",
  "technical_progress.file_edit.failure": "Échec de la modification du fichier",
  "technical_progress.file_edit.empty": "Fichier modifié",
  "technical_progress.file_create.running": "Création du fichier en cours",
  "technical_progress.file_create.success": "Fichier créé",
  "technical_progress.file_create.failure": "Échec de la création du fichier",
  "technical_progress.file_create.empty": "Fichier créé",
  "technical_progress.file_delete.running": "Suppression du fichier en cours",
  "technical_progress.file_delete.success": "Fichier supprimé",
  "technical_progress.file_delete.failure": "Échec de la suppression du fichier",
  "technical_progress.file_delete.empty": "Fichier supprimé",
  "technical_progress.patch.running": "Application du patch en cours",
  "technical_progress.patch.success": "Patch appliqué",
  "technical_progress.patch.failure": "Échec de l'application du patch",
  "technical_progress.patch.empty": "Patch appliqué",
  "technical_progress.command.running": "Exécution de la commande en cours",
  "technical_progress.command.success": "Commande exécutée",
  "technical_progress.command.failure": "Échec de la commande",
  "technical_progress.command.empty": "Commande exécutée",
  "technical_progress.project_search.running": "Recherche dans le projet en cours",
  "technical_progress.project_search.success": "Correspondances trouvées",
  "technical_progress.project_search.failure": "Échec de la recherche",
  "technical_progress.project_search.empty": "Aucune correspondance trouvée",
  "technical_progress.web_search.running": "Recherche web en cours",
  "technical_progress.web_search.success": "Recherche web effectuée",
  "technical_progress.web_search.failure": "Échec de la recherche web",
  "technical_progress.web_search.empty": "Aucun résultat web trouvé",
  "technical_progress.web_read.running": "Lecture de la page en cours",
  "technical_progress.web_read.success": "Page lue",
  "technical_progress.web_read.failure": "Échec de la lecture de la page",
  "technical_progress.web_read.empty": "Page lue",
  "technical_progress.reasoning.running": "Réflexion en cours",
  "technical_progress.reasoning.success": "Réflexion terminée",
  "technical_progress.reasoning.failure": "Échec de la réflexion",
  "technical_progress.reasoning.empty": "Réflexion terminée",
  "technical_progress.skill.running": "Exécution de la skill en cours",
  "technical_progress.skill.success": "Skill exécutée",
  "technical_progress.skill.failure": "Échec de la skill",
  "technical_progress.skill.empty": "Skill exécutée",
  "technical_progress.subagent.running": "Le sous-agent travaille",
  "technical_progress.subagent.success": "Sous-agent terminé",
  "technical_progress.subagent.failure": "Échec du sous-agent",
  "technical_progress.subagent.empty": "Sous-agent terminé",
  "technical_progress.mcp.running": "Exécution de l'outil MCP en cours",
  "technical_progress.mcp.success": "Outil MCP terminé",
  "technical_progress.mcp.failure": "Échec de l'outil MCP",
  "technical_progress.mcp.empty": "Outil MCP terminé",
  "technical_progress.todo.running": "Mise à jour de la liste des tâches",
  "technical_progress.todo.success": "Liste des tâches mise à jour",
  "technical_progress.todo.failure": "Échec de la mise à jour de la liste des tâches",
  "technical_progress.todo.empty": "Liste des tâches mise à jour",
  "technical_progress.network.running": "Requête réseau en cours",
  "technical_progress.network.success": "Requête réseau terminée",
  "technical_progress.network.failure": "Échec de la requête réseau",
  "technical_progress.network.empty": "Requête réseau terminée",
  "technical_progress.package.running": "Mise à jour du paquet en cours",
  "technical_progress.package.success": "Paquet mis à jour",
  "technical_progress.package.failure": "Échec de l'opération sur le paquet",
  "technical_progress.package.empty": "Paquet mis à jour",
  "technical_progress.build.running": "Compilation en cours",
  "technical_progress.build.success": "Compilation terminée",
  "technical_progress.build.failure": "Échec de la compilation",
  "technical_progress.build.empty": "Compilation terminée",
  "technical_progress.test.running": "Exécution des tests en cours",
  "technical_progress.test.success": "Tests terminés",
  "technical_progress.test.failure": "Échec des tests",
  "technical_progress.test.empty": "Tests terminés",
  "technical_progress.generic.running": "Exécution de l'action en cours",
  "technical_progress.generic.success": "Action terminée",
  "technical_progress.generic.failure": "Échec de l'action",
  "technical_progress.generic.empty": "Action terminée",
  "technical_progress.todo.updated": "📝 Liste des tâches mise à jour — {count} {unit}",
  "technical_progress.todo.all_done": "✅ Toutes les tâches terminées",
  "technical_progress.unit.line.one": "ligne",
  "technical_progress.unit.line.few": "lignes",
  "technical_progress.unit.line.many": "lignes",
  "technical_progress.unit.line.other": "lignes",
  "technical_progress.unit.result.one": "résultat",
  "technical_progress.unit.result.few": "résultats",
  "technical_progress.unit.result.many": "résultats",
  "technical_progress.unit.result.other": "résultats",
  "technical_progress.unit.task.one": "tâche",
  "technical_progress.unit.task.few": "tâches",
  "technical_progress.unit.task.many": "tâches",
  "technical_progress.unit.task.other": "tâches",
  "technical_progress.unit.item.one": "élément",
  "technical_progress.unit.item.few": "éléments",
  "technical_progress.unit.item.many": "éléments",
  "technical_progress.unit.item.other": "éléments",

  "agent.mode.plan": "L'agent planifie avant d'agir ; aucun code n'est modifié",
  "agent.mode.build": "Les modifications de code sont appliquées directement aux fichiers",
  "agent.mode.general": "Agent polyvalent pour n'importe quelle tâche",
  "agent.mode.explore": "Recherche rapide de fichiers et de motifs de code",
  "agent.mode.title": "Génère un titre de session à partir de la conversation",
  "agent.mode.summary": "Compresse l'historique de la conversation en un résumé",
  "agent.mode.compaction": "Résume les anciens messages pour libérer du contexte",
  "agent.mode.custom": "Mode d'agent personnalisé",

  "terminal.open_button": "🖥 Ouvrir le Terminal",
  "terminal.created": "🖥 Sujet de terminal créé : {title}",
  "terminal.new_topic_name": "📓 Nouveau terminal",
  "terminal.topic_name": "📓 Terminal : {command}",

  "keyboard.new_window": "➕ Nouvelle fenêtre",
  "keyboard.stop": "⏹ Arrêter",
  "keyboard.new_window_created": "✅ Nouvelle fenêtre de terminal créée.",

  "reasoning.title": "🧠 Paramètres de réflexion",
  "reasoning.mode_0": "0 - Réponse finale uniquement",
  "reasoning.mode_1": "1 - Pensées et fichiers",
  "reasoning.mode_2": "2 - Niveau 1 + commandes + messages d'outils séparés (par défaut)",
  "reasoning.current": "Mode actuel : {mode}",
  "reasoning.updated": "✅ Mode de réflexion défini sur : {mode}",

  "cmd.description.compact": "Compacter le contexte de la session actuelle",
  "cmd.description.terminal": "Ouvrir une fenêtre de terminal",
  "error.user_not_found": "❌ Utilisateur introuvable.",
  "bot.session_recreated_remote": "🔄 Session recréée sur le serveur distant.",

  "goal.described": "🎯 Objectif décrit",
  "goal.paused": "⏸ Objectif suspendu",
  "goal.resumed": "▶️ Objectif repris",
  "goal.cleared": "🧹 Objectif effacé",
  "goal.no_session": "❌ Aucune session active",
  "goal.set": "🎯 Objectif défini",
  "goal.error": "❌ Erreur d'objectif",

  "ssh.prompt.conn_str": "🔌 Veuillez envoyer la chaîne de connexion SSH au format `username@host:port` (ex. `root@192.168.1.100:22`)",
  "ssh.prompt.auth_method": "🔑 Sélectionnez la méthode d'authentification SSH :",
  "ssh.prompt.password": "💬 Veuillez envoyer votre mot de passe SSH :",
  "ssh.prompt.private_key": "📝 Veuillez coller le contenu de votre clé privée SSH :",
  "ssh.prompt.target": "🚀 Sélectionnez la cible de déploiement pour le serveur OpenCode :",
  "ssh.success": "✅ Connexion SSH et tunnel OpenCode établis avec succès !",
  "ssh.error": "🔴 Erreur de configuration SSH : {error}",
  "ssh.button.password": "🔑 Mot de passe",
  "ssh.button.private_key": "📝 Clé privée",
  "ssh.button.docker": "🐳 Conteneur Docker",
  "ssh.button.host": "💻 Système hôte",
  "ssh.button.cancel": "❌ Annuler",
  "ssh.cancelled": "❌ Configuration SSH annulée.",
  "ssh.active_status": "🟢 SSH actif : {username}@{host}:{port}",
  "ssh.button.disconnect": "🔌 Se déconnecter",
  "ssh.button.new_connection": "➕ Nouvelle connexion",
  "ssh.saved_connections_title": "📋 Connexions SSH enregistrées :",
  "ssh.no_saved_connections": "Aucune connexion SSH enregistrée trouvée.",
  "ssh.connection_deleted": "🗑️ Connexion supprimée.",
  "ssh.invalid_format": "❌ Format invalide. Exemple : root@192.168.1.1:22",
  "ssh.connection_not_found": "Connexion introuvable.",
  "ssh.connecting_saved": "⏳ Connexion au serveur enregistré...",

  "model.menu.add_provider": "Ajouter un fournisseur",
  "mcp.oauth_error": "Échec de l'OAuth MCP : {error}",
  "mcp.oauth_success": "OAuth MCP terminé pour {name}.",
  "mcp.oauth_starting": "Démarrage de l'OAuth pour {name}...",
  "mcps.button.oauth": "S'authentifier",
  "share.unshared": "Partage de session révoqué.",
  "share.unshare_error": "Impossible de révoquer le partage de session.",
  "share.success": "Session partagée : {url}",
  "share.error": "Impossible de partager la session.",
  "share.no_session": "Aucune session active à partager.",
  "cmd.description.share": "Partager la session actuelle",
  "server.unavailable": "Le serveur est indisponible.",
  "server.healthy": "Le serveur est sain.",
  "server.credentials": "Identifiant : ||{user}||\nMot de passe : ||{pass}||",
  "server.info": "Serveur OpenCode : {url}",
  "cmd.description.server": "Panneau Web OpenCode",

  "connect.oauth_polling": "En attente d'autorisation... Le serveur la détectera automatiquement (le navigateur doit être sur la même machine).",
  "connect.oauth_checking": "Vérification du statut d'autorisation...",
  "connect.oauth_timeout": "Délai d'autorisation dépassé pour {name}. Veuillez réessayer ou utiliser la méthode de clé API.",
  "connect.ready": "Le serveur a redémarré.",
  "connect.restarting": "Redémarrage du serveur...",
  "connect.enter_key": "Entrez la clé API pour {name} :",
  "connect.no_methods": "Aucune méthode d'authentification disponible.",
  "connect.choose_method": "Choisissez la méthode d'authentification :",
  "connect.pick": "Sélectionnez un fournisseur :",
  "connect.authorized": "Autorisé avec succès auprès du fournisseur.",
  "connect.auth_url": "Ouvrez cette URL pour vous authentifier :\n{url}",
  "connect.auth_error": "Échec de l'authentification. Veuillez réessayer.",
  "connect.select": "Sélectionnez un fournisseur à connecter :",
  "connect.empty": "Aucun fournisseur d'IA configuré.",
  "connect.error": "Impossible de lister les fournisseurs.",
  "cmd.description.connect": "Connecter les fournisseurs d'IA",

  "cmd.description.fork": "Diviser la session dans un nouveau sujet",
  "fork.success": "Session divisée : {title}. Ouverture dans un nouveau sujet...",
  "fork.no_session": "Aucune session active à diviser.",
  "fork.error": "Impossible de diviser la session.",
  "share.already_shared": "Session déjà partagée : {url}",
  "edit.fork_or_revert": "Message modifié. Choisissez une action :",
  "edit.fork_button": "Diviser dans un nouveau sujet",
  "edit.revert_button": "Revenir à ce message",
  "edit.no_session": "Impossible de traiter le message modifié : aucune session active.",
  "edit.not_found": "Le message modifié n'est pas suivi dans le journal.",
  "cmd.description.revert": "Revenir à la session du message répondu",
  "cmd.description.del": "Supprimer le message répondu",
  "revert.no_reply": "Répondez à un message avec /revert pour y revenir.",
  "revert.no_session": "Aucune session active.",
  "revert.error": "Impossible de revenir à l'état de la session.",
  "revert.success": "Session rétablie. Messages supprimés du sujet.",
  "del.no_reply": "Répondez à un message avec /del pour le supprimer.",
  "del.success": "Message supprimé.",
  "del.error": "Impossible de supprimer le message.",
  "bookmark.saved": "❤️ Message ajouté aux favoris.",
  "bookmark.removed": "Favori supprimé.",
  "react.abort": "💔 Opération annulée.",
  "cmd.description.memory": "Afficher la mémoire du projet (MEMORY.md)",
  "memory.empty": "MEMORY.md introuvable. Utilisez /memory add <texte> pour créer.",
  "memory.added": "Entrée ajoutée à MEMORY.md.",
  "memory.usage": "Usage : /memory [add <texte>] — afficher ou ajouter à la mémoire.",
  "memory.show": "Mémoire du projet (MEMORY.md) :",
  "memory.show_truncated": "(affichage des 2000 premiers caractères)"
};

const zhTranslations: Record<string, string> = {
  "worktree.already_selected_callback": "此工作树已被选择",
  "worktree.empty": "📭 未找到当前仓库的 git 工作树。",
  "worktree.fetch_error": "🔴 加载 git 工作树失败。",
  "worktree.not_git_repo": "🌿 当前项目无法使用 git 工作树。请先选择一个 git 仓库。",
  "worktree.not_git_repo_callback": "当前项目不是 git 仓库",
  "worktree.page_empty_callback": "此页面没有工作树",
  "worktree.project_not_selected": "🏗 未选择项目。\n\n请先使用 /projects 选择一个项目。",
  "worktree.select_error": "🔴 选择工作树失败。",
  "worktree.select_with_current": "请选择一个工作树：",
  "worktree.selected": "✅ 已选择工作树：{worktree}\n\n📋 会话已重置。请使用 /sessions 或 /new 继续。",
  "worktree.selection_missing_callback": "所选工作树已不再可用",

  "technical_progress.file_read.running": "正在读取文件",
  "technical_progress.file_read.success": "已读取文件",
  "technical_progress.file_read.failure": "读取文件失败",
  "technical_progress.file_read.empty": "已读取文件",
  "technical_progress.directory_read.running": "正在读取目录",
  "technical_progress.directory_read.success": "已读取目录",
  "technical_progress.directory_read.failure": "读取目录失败",
  "technical_progress.directory_read.empty": "已读取目录",
  "technical_progress.file_write.running": "正在写入文件",
  "technical_progress.file_write.success": "已写入文件",
  "technical_progress.file_write.failure": "写入文件失败",
  "technical_progress.file_write.empty": "已写入文件",
  "technical_progress.file_edit.running": "正在编辑文件",
  "technical_progress.file_edit.success": "已编辑文件",
  "technical_progress.file_edit.failure": "编辑文件失败",
  "technical_progress.file_edit.empty": "已编辑文件",
  "technical_progress.file_create.running": "正在创建文件",
  "technical_progress.file_create.success": "已创建文件",
  "technical_progress.file_create.failure": "创建文件失败",
  "technical_progress.file_create.empty": "已创建文件",
  "technical_progress.file_delete.running": "正在删除文件",
  "technical_progress.file_delete.success": "已删除文件",
  "technical_progress.file_delete.failure": "删除文件失败",
  "technical_progress.file_delete.empty": "已删除文件",
  "technical_progress.patch.running": "正在应用补丁",
  "technical_progress.patch.success": "已应用补丁",
  "technical_progress.patch.failure": "应用补丁失败",
  "technical_progress.patch.empty": "已应用补丁",
  "technical_progress.command.running": "正在运行命令",
  "technical_progress.command.success": "已运行命令",
  "technical_progress.command.failure": "命令运行失败",
  "technical_progress.command.empty": "已运行命令",
  "technical_progress.project_search.running": "正在搜索项目",
  "technical_progress.project_search.success": "找到匹配项",
  "technical_progress.project_search.failure": "搜索项目失败",
  "technical_progress.project_search.empty": "未找到匹配项",
  "technical_progress.web_search.running": "正在搜索网络",
  "technical_progress.web_search.success": "已完成网页搜索",
  "technical_progress.web_search.failure": "网页搜索失败",
  "technical_progress.web_search.empty": "未找到网页结果",
  "technical_progress.web_read.running": "正在读取网页",
  "technical_progress.web_read.success": "已读取网页",
  "technical_progress.web_read.failure": "读取网页失败",
  "technical_progress.web_read.empty": "已读取网页",
  "technical_progress.reasoning.running": "正在思考",
  "technical_progress.reasoning.success": "完成推理",
  "technical_progress.reasoning.failure": "推理失败",
  "technical_progress.reasoning.empty": "完成推理",
  "technical_progress.skill.running": "正在执行技能",
  "technical_progress.skill.success": "技能执行完成",
  "technical_progress.skill.failure": "技能执行失败",
  "technical_progress.skill.empty": "技能执行完成",
  "technical_progress.subagent.running": "子代理正在工作",
  "technical_progress.subagent.success": "子代理已完成",
  "technical_progress.subagent.failure": "子代理执行失败",
  "technical_progress.subagent.empty": "子代理已完成",
  "technical_progress.mcp.running": "正在运行 MCP 工具",
  "technical_progress.mcp.success": "MCP 工具执行完成",
  "technical_progress.mcp.failure": "MCP 工具执行失败",
  "technical_progress.mcp.empty": "MCP 工具执行完成",
  "technical_progress.todo.running": "正在更新任务列表",
  "technical_progress.todo.success": "已更新任务列表",
  "technical_progress.todo.failure": "更新任务列表失败",
  "technical_progress.todo.empty": "已更新任务列表",
  "technical_progress.network.running": "正在进行网络请求",
  "technical_progress.network.success": "网络请求已完成",
  "technical_progress.network.failure": "网络请求失败",
  "technical_progress.network.empty": "网络请求已完成",
  "technical_progress.package.running": "正在更新包",
  "technical_progress.package.success": "已更新包",
  "technical_progress.package.failure": "包操作失败",
  "technical_progress.package.empty": "已更新包",
  "technical_progress.build.running": "正在构建",
  "technical_progress.build.success": "构建已完成",
  "technical_progress.build.failure": "构建失败",
  "technical_progress.build.empty": "构建已完成",
  "technical_progress.test.running": "正在运行测试",
  "technical_progress.test.success": "测试已完成",
  "technical_progress.test.failure": "测试失败",
  "technical_progress.test.empty": "测试已完成",
  "technical_progress.generic.running": "正在执行操作",
  "technical_progress.generic.success": "操作已完成",
  "technical_progress.generic.failure": "操作失败",
  "technical_progress.generic.empty": "操作已完成",
  "technical_progress.todo.updated": "📝 已更新任务列表 — {count} {unit}",
  "technical_progress.todo.all_done": "✅ 所有任务已完成",
  "technical_progress.unit.line.one": "行",
  "technical_progress.unit.line.few": "行",
  "technical_progress.unit.line.many": "行",
  "technical_progress.unit.line.other": "行",
  "technical_progress.unit.result.one": "个结果",
  "technical_progress.unit.result.few": "个结果",
  "technical_progress.unit.result.many": "个结果",
  "technical_progress.unit.result.other": "个结果",
  "technical_progress.unit.task.one": "个任务",
  "technical_progress.unit.task.few": "个任务",
  "technical_progress.unit.task.many": "个任务",
  "technical_progress.unit.task.other": "个任务",
  "technical_progress.unit.item.one": "个项目",
  "technical_progress.unit.item.few": "个项目",
  "technical_progress.unit.item.many": "个项目",
  "technical_progress.unit.item.other": "个项目",

  "agent.mode.plan": "代理在行动前进行规划，不修改 any 代码",
  "agent.mode.build": "代码变更直接应用到文件中",
  "agent.mode.general": "适用于任何任务的通用代理",
  "agent.mode.explore": "快速的文件和代码模式搜索",
  "agent.mode.title": "根据对话生成会话标题",
  "agent.mode.summary": "将对话历史压缩为摘要",
  "agent.mode.compaction": "总结旧消息以释放上下文空间",
  "agent.mode.custom": "自定义代理模式",

  "terminal.open_button": "🖥 打开终端",
  "terminal.created": "🖥 终端主题已创建：{title}",
  "terminal.new_topic_name": "📓 新终端",
  "terminal.topic_name": "📓 终端：{command}",

  "keyboard.new_window": "➕ 新窗口",
  "keyboard.stop": "⏹ 停止",
  "keyboard.new_window_created": "✅ 新终端窗口已创建。",

  "reasoning.title": "🧠 推理设置",
  "reasoning.mode_0": "0 - 仅最终回答",
  "reasoning.mode_1": "1 - 思考内容和文件",
  "reasoning.mode_2": "2 - 级别 1 + 命令 + 独立的工具消息（默认）",
  "reasoning.current": "当前模式：{mode}",
  "reasoning.updated": "✅ 推理模式已切换为：{mode}",

  "cmd.description.compact": "压缩当前会话的上下文",
  "cmd.description.terminal": "打开终端窗口",
  "error.user_not_found": "❌ 未找到用户。",
  "bot.session_recreated_remote": "🔄 已在远程服务器上重新创建会话。",

  "goal.described": "🎯 目标已描述",
  "goal.paused": "⏸ 目标已暂停",
  "goal.resumed": "▶️ 目标已恢复",
  "goal.cleared": "🧹 目标已清除",
  "goal.no_session": "❌ 无活动会话",
  "goal.set": "🎯 目标已设置",
  "goal.error": "❌ 目标错误",

  "ssh.prompt.conn_str": "🔌 请发送 SSH 连接字符串，格式为 `username@host:port`（例如 `root@192.168.1.100:22`）",
  "ssh.prompt.auth_method": "🔑 选择 SSH 身份验证方式：",
  "ssh.prompt.password": "💬 请发送你的 SSH 密码：",
  "ssh.prompt.private_key": "📝 请粘贴你的 SSH 私钥内容：",
  "ssh.prompt.target": "🚀 选择 OpenCode 服务器的部署目标：",
  "ssh.success": "✅ SSH 连接和 OpenCode 隧道已成功建立！",
  "ssh.error": "🔴 SSH 设置错误：{error}",
  "ssh.button.password": "🔑 密码",
  "ssh.button.private_key": "📝 私钥",
  "ssh.button.docker": "🐳 Docker 容器",
  "ssh.button.host": "💻 主机系统",
  "ssh.button.cancel": "❌ 取消",
  "ssh.cancelled": "❌ SSH 配置已取消。",
  "ssh.active_status": "🟢 SSH 已激活：{username}@{host}:{port}",
  "ssh.button.disconnect": "🔌 断开连接",
  "ssh.button.new_connection": "➕ 新建连接",
  "ssh.saved_connections_title": "📋 已保存的 SSH 连接：",
  "ssh.no_saved_connections": "未找到已保存的 SSH 连接。",
  "ssh.connection_deleted": "🗑️ 连接已删除。",
  "ssh.invalid_format": "❌ 格式无效。示例：root@192.168.1.1:22",
  "ssh.connection_not_found": "未找到连接。",
  "ssh.connecting_saved": "⏳ 正在连接到已保存的服务器...",

  "model.menu.add_provider": "添加提供方",
  "mcp.oauth_error": "MCP OAuth 失败：{error}",
  "mcp.oauth_success": "已完成 {name} 的 MCP OAuth。",
  "mcp.oauth_starting": "正在启动 {name} 的 OAuth...",
  "mcps.button.oauth": "身份验证",
  "share.unshared": "会话共享已被撤销。",
  "share.unshare_error": "取消会话共享失败。",
  "share.success": "会话已共享：{url}",
  "share.error": "共享会话失败。",
  "share.no_session": "没有可共享的活动会话。",
  "cmd.description.share": "共享当前会话",
  "server.unavailable": "服务器不可用。",
  "server.healthy": "服务器健康。",
  "server.credentials": "登录名：||{user}||\n密码：||{pass}||",
  "server.info": "OpenCode 服务器：{url}",
  "cmd.description.server": "OpenCode 网页面板",

  "connect.oauth_polling": "正在等待授权... 服务器会自动检测（浏览器必须在同一台机器上）。",
  "connect.oauth_checking": "正在检查授权状态...",
  "connect.oauth_timeout": "已超时 {name} 的授权。请重试或使用 API 密钥方式。",
  "connect.ready": "服务器已重启。",
  "connect.restarting": "正在重启服务器...",
  "connect.enter_key": "请输入 {name} 的 API 密钥：",
  "connect.no_methods": "无可用身份验证方式。",
  "connect.choose_method": "选择身份验证方式：",
  "connect.pick": "选择提供方：",
  "connect.authorized": "已成功与提供方完成授权。",
  "connect.auth_url": "打开此 URL 进行身份验证：\n{url}",
  "connect.auth_error": "身份验证失败。请重试。",
  "connect.select": "选择要连接的提供方：",
  "connect.empty": "未配置 AI 提供方。",
  "connect.error": "获取提供方列表失败。",
  "cmd.description.connect": "连接 AI 提供方",

  "cmd.description.fork": "工作会话分叉到新话题",
  "fork.success": "会话已分叉：{title}。正在新话题中打开...",
  "fork.no_session": "没有可分叉的活动会话。",
  "fork.error": "分叉会话失败。",
  "share.already_shared": "会话已共享：{url}",
  "edit.fork_or_revert": "消息已编辑。选择操作：",
  "edit.fork_button": "在新话题中分叉",
  "edit.revert_button": "回滚到此消息",
  "edit.no_session": "无法处理已编辑的消息：没有活动会话。",
  "edit.not_found": "已编辑的消息未在日志中记录。",
  "cmd.description.revert": "将会话回滚到被回复的消息",
  "cmd.description.del": "删除被回复的消息",
  "revert.no_reply": "回复一条消息并发送 /revert 以回滚到该消息。",
  "revert.no_session": "没有活动会话。",
  "revert.error": "回滚会话失败。",
  "revert.success": "会话已回滚。消息已从话题中删除。",
  "del.no_reply": "回复一条消息并发送 /del 以将其删除。",
  "del.success": "消息已删除。",
  "del.error": "删除消息失败。",
  "bookmark.saved": "❤️ 消息已加入书签。",
  "bookmark.removed": "书签已移除。",
  "react.abort": "💔 操作已中止。",
  "cmd.description.memory": "显示项目记忆 (MEMORY.md)",
  "memory.empty": "MEMORY.md 未找到。使用 /memory add <文本> 创建。",
  "memory.added": "条目已添加到 MEMORY.md。",
  "memory.usage": "用法: /memory [add <文本>] — 显示或添加到项目记忆。",
  "memory.show": "项目记忆 (MEMORY.md):",
  "memory.show_truncated": "(显示前 2000 个字符)"
};

const configs = [
  { file: "../src/i18n/de.ts", name: "de", original: originalDe, trans: deTranslations },
  { file: "../src/i18n/es.ts", name: "es", original: originalEs, trans: esTranslations },
  { file: "../src/i18n/fr.ts", name: "fr", original: originalFr, trans: frTranslations },
  { file: "../src/i18n/zh.ts", name: "zh", original: originalZh, trans: zhTranslations }
];

for (const config of configs) {
  const merged: Record<string, string> = {};
  for (const key of Object.keys(en)) {
    if (config.trans[key] !== undefined) {
      merged[key] = config.trans[key];
    } else if ((config.original as any)[key] !== undefined && (config.original as any)[key] !== "") {
      merged[key] = (config.original as any)[key];
    } else {
      merged[key] = (en as any)[key];
    }
  }

  // Format content as clean TypeScript
  let content = `import type { I18nDictionary } from "./en.js";\n\n`;
  content += `export const ${config.name}: I18nDictionary = {\n`;
  for (const [key, value] of Object.entries(merged)) {
    const escapedValue = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
    content += `  "${key}": "${escapedValue}",\n`;
  }
  content += `};\n`;

  fs.writeFileSync(path.resolve(__dirname, config.file), content, "utf-8");
  console.log(`Updated ${config.file}`);
}
